name: Deployment

on:
  push:
    branches:
      - main

jobs:
  queue-ratings:
    runs-on: ubuntu-latest
    steps:
      - name: Queue Ratings for Production
        run: |
          curl -X POST https://gdcheerios.com/queue-ratings \
               -H "Authorization: Bearer ${{ secrets.SECRET }}" \
               -H "Content-Type: application/json" \
               -d '{"environment": "Production"}'

      - name: Queue Ratings for Development
        run: |
          curl -X POST https://dev.gdcheerios.com/queue-ratings \
               -H "Authorization: Bearer ${{ secrets.SECRET }}" \
               -H "Content-Type: application/json" \
               -d '{"environment": "Development"}'
